name: "build1.20.4"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  call-build:
    uses: "jpenilla/actions/.github/workflows/shared-ci.yml@master"
    secrets: inherit
    with:
      modrinth-publish: true
      artifacts-path: 'build/libs/better-fabric-console-mc*.jar'
      loom: true
